spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sungwonkim
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true